# Generated by Django 6.0.6 on 2026-06-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='interims/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(default='Leader', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pseudo', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/')),
                ('slogan', models.CharField(blank=True, max_length=255)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='WarToWin', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('welcome_text', models.TextField()),
            ],
        ),
    ]
