# Generated by Django 6.0.6 on 2026-06-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recruitmentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=120)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('request_type', models.CharField(choices=[('tvt', 'TvT'), ('tvg', 'TvG')], max_length=10)),
                ('requested_at', models.DateTimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Acceptee'), ('rejected', 'Refusee')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['requested_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='interim',
            name='ff_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='interims/ff_profiles/'),
        ),
        migrations.AddField(
            model_name='leader',
            name='ff_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='leaders/ff_profiles/'),
        ),
        migrations.AddField(
            model_name='member',
            name='ff_profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='members/ff_profiles/'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='facebook_profile',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='team_tag',
            field=models.CharField(default='W2W', max_length=20),
        ),
    ]
