# Generated by Django 6.0.6 on 2026-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matchrequest_interim_ff_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamsettings',
            name='accent_color',
            field=models.CharField(default='#00b16a', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='background_color',
            field=models.CharField(default='#050507', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='background_soft_color',
            field=models.CharField(default='#0f0a0d', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='card_color',
            field=models.CharField(default='#121116', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='card_soft_color',
            field=models.CharField(default='#17141c', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='font_choice',
            field=models.CharField(choices=[('orbitron', 'Orbitron + Inter'), ('poppins', 'Poppins'), ('rajdhani', 'Rajdhani')], default='orbitron', max_length=20),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='muted_color',
            field=models.CharField(default='#a7acba', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='primary_color',
            field=models.CharField(default='#ff274b', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='primary_soft_color',
            field=models.CharField(default='#ff5c78', max_length=7),
        ),
        migrations.AddField(
            model_name='teamsettings',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
